# Generated by Django 3.0.5 on 2020-04-11 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userimage',
            old_name='image',
            new_name='image_file',
        ),
        migrations.AddField(
            model_name='userimage',
            name='image_id',
            field=models.CharField(default='pic1', max_length=10),
        ),
    ]
