# Generated by Django 3.0.5 on 2020-04-16 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0002_auto_20200411_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='userimage',
            name='session_id',
            field=models.CharField(default='42', max_length=128),
        ),
    ]
